import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { doctorCmd } from "../src/commands/doctor";

const ROOT = fileURLToPath(new URL("..", import.meta.url));

for (const name of ["cli-tool", "demo-run", "electron-app", "frontend-spa", "npm-lib"]) {
  test(`example ${name} stays doctor-healthy`, () => {
    const original = process.stdout.write.bind(process.stdout);
    const chunks: string[] = [];
    (process.stdout as unknown as { write: (chunk: string | Uint8Array) => boolean }).write = (chunk) => {
      chunks.push(String(chunk));
      return true;
    };
    let code: number;
    try {
      code = doctorCmd(join(ROOT, "examples", name));
    } finally {
      (process.stdout as unknown as { write: typeof process.stdout.write }).write = original;
    }
    assert.equal(code, 0, chunks.join(""));
  });

  test(`example ${name} keeps a short entrypoint with a generated reference catalog`, () => {
    const repo = join(ROOT, "examples", name);
    const agents = readFileSync(join(repo, "AGENTS.md"), "utf8");
    const reference = readFileSync(join(repo, ".agents", "reference.md"), "utf8");

    assert.match(agents, /Full commands, environment, and registered knowledge catalog: `.agents\/reference\.md`/);
    assert.match(agents, /Read `NEXT ACTIONS`/);
    assert.match(agents, /complete every `required \| agent` action automatically/);
    assert.match(agents, /Informational boundaries.*are not failures/);
    assert.match(reference, /^<!-- GENERATED by ai-harness/m);
    assert.match(reference, /^# Harness reference$/m);
    assert.match(reference, /^## Commands$/m);
    assert.match(reference, /^## Registered knowledge$/m);
  });
}

test("frontend and Electron gate examples contain real package scripts and executable test bodies", () => {
  const frontend = join(ROOT, "examples", "frontend-spa");
  const frontendPackage = JSON.parse(readFileSync(join(frontend, "package.json"), "utf8"));
  assert.equal(frontendPackage.scripts.e2e, "playwright test");
  assert.match(readFileSync(join(frontend, "pnpm-workspace.yaml"), "utf8"), /allowBuilds:[\s\S]*esbuild: true/);
  assert.match(readFileSync(join(frontend, "e2e", "dashboard.spec.ts"), "utf8"), /test\([\s\S]*page\.goto/);

  const electron = join(ROOT, "examples", "electron-app");
  const electronPackage = JSON.parse(readFileSync(join(electron, "package.json"), "utf8"));
  assert.match(electronPackage.scripts["test:e2e:renderer"], /playwright test/);
  assert.match(electronPackage.scripts["test:e2e:electron"], /playwright test/);
  assert.match(readFileSync(join(electron, "pnpm-workspace.yaml"), "utf8"), /allowBuilds:[\s\S]*electron: true/);
  assert.match(readFileSync(join(electron, "e2e", "renderer", "navigation.spec.mjs"), "utf8"), /test\([\s\S]*page\.goto/);
  assert.match(readFileSync(join(electron, "e2e", "electron", "ipc.spec.mjs"), "utf8"), /electron\.launch[\s\S]*notes:list|electron\.launch[\s\S]*Load notes/);
});

