import { test } from "node:test";
import assert from "node:assert/strict";
import { renderAgentsMd, renderTargets } from "../src/render";
import type { Manifest } from "../src/manifest";

const base: Manifest = {
  spec: "ai-harness/v0",
  identity: { name: "demo", summary: "a demo project" },
  capabilities: { test: { run: "pnpm test" } },
};

test("AGENTS.md carries the GEN header, the working agreement and commands", () => {
  const md = renderAgentsMd(base);
  assert.match(md, /GENERATED by ai-harness/);
  assert.match(md, /Working agreement/);
  assert.match(md, /Task Brief/);
  assert.match(md, /NEXT ACTIONS/);
  assert.match(md, /required \| agent/);
  assert.match(md, /ask the user only for a `required \| human` decision/);
  assert.match(md, /Informational boundaries.*are not failures/);
  assert.match(md, /pnpm test/);
});

test("renderTargets omits routing/modules when absent and adds them when present", () => {
  const bare = renderTargets(base).map((t) => t[0]);
  assert.ok(bare.includes("AGENTS.md"));
  assert.ok(bare.includes("CLAUDE.md"));
  assert.ok(bare.includes(".agents/reference.md"));
  assert.ok(!bare.some((p) => p.includes(".cursor")));
  assert.ok(!bare.includes(".agents/routing.md"));
  assert.ok(!bare.includes(".agents/modules.md"));

  const rich = renderTargets({
    ...base,
    routing: [{ when: "fix a bug", read: ["src/a.ts"] }],
    modules: [{ name: "m", role: "r", entry: ["src/a.ts"] }],
  }).map((t) => t[0]);
  assert.ok(rich.includes(".agents/routing.md"));
  assert.ok(rich.includes(".agents/modules.md"));
});

test("even an empty catalog gets the reference target promised by AGENTS.md", () => {
  const minimal: Manifest = { spec: "ai-harness/v0", identity: { name: "minimal" } };
  const targets = renderTargets(minimal);
  const agents = targets.find(([path]) => path === "AGENTS.md")?.[1] ?? "";
  const reference = targets.find(([path]) => path === ".agents/reference.md")?.[1] ?? "";

  assert.match(agents, /`\.agents\/reference\.md`/);
  assert.match(reference, /^# Harness reference$/m);
});

test("AGENTS keeps bootstrap commands short while reference.md preserves the full catalog", () => {
  const manifest: Manifest = {
    ...base,
    capabilities: {
      test: { run: "pnpm test", bootstrap: true },
      releaseInternalCandidate: { run: "pnpm release:internal:candidate", desc: "long release description" },
    },
    environment: [{ name: "DATABASE_URL", desc: "database connection", required: true, secret: true }],
    knowledge: [
      { root: "repo", path: "engineering/handbook/api.md", role: "api", authority: "derived" },
      { root: "agents", path: "knowledge/policy.md", role: "policy", authority: "policy" },
    ],
  };
  const agents = renderAgentsMd(manifest);
  assert.match(agents, /pnpm test/);
  assert.doesNotMatch(agents, /release:internal:candidate/);
  assert.doesNotMatch(agents, /DATABASE_URL/);
  assert.match(agents, /\.agents\/reference\.md/);
  assert.match(agents, /Existing repository documents stay in place/);

  const reference = renderTargets(manifest).find((target) => target[0] === ".agents/reference.md")![1];
  assert.match(reference, /release:internal:candidate/);
  assert.match(reference, /DATABASE_URL/);
  assert.match(reference, /engineering\/handbook\/api\.md/);
  assert.match(reference, /\.agents\/knowledge\/policy\.md/);
});

test("routing step in AGENTS.md adapts to whether routing exists", () => {
  assert.match(renderAgentsMd(base), /Read the relevant files before editing/);
  assert.match(
    renderAgentsMd({ ...base, routing: [{ when: "fix" }] }),
    /routing\.md/,
  );
});

test("modules.md renders impact fields and the project-defined validation gate catalog", () => {
  const targets = renderTargets({
    ...base,
    spec: "ai-harness/v1",
    capabilities: { test: { run: "pnpm test" }, e2e: { run: "pnpm e2e" } },
    modules: [
      {
        name: "api",
        role: "r",
        entry: ["src/api/index.ts"],
        owns: ["src/api/**"],
        tests: ["test/api/**"],
        checks: ["test"],
        gates: ["user-flow"],
        test_touch: "required",
        playbook: "verify-api.md",
      },
    ],
    validation: {
      gates: {
        "user-flow": {
          desc: "exercise the observable flow",
          checks: ["e2e"],
          acceptance: { tests: ["e2e/**"], test_touch: "required" },
        },
      },
    },
  });
  const modulesMd = targets.find((t) => t[0] === ".agents/modules.md")![1];
  assert.match(modulesMd, /Owns \(prod\):.*src\/api/);
  assert.match(modulesMd, /Tests:.*test\/api/);
  assert.match(modulesMd, /Checks:.*test/);
  assert.match(modulesMd, /Validation gates:.*user-flow/);
  assert.match(modulesMd, /Test touch:.*required/);
  assert.match(modulesMd, /Playbook:.*verify-api\.md/);
  assert.match(modulesMd, /# Validation gates/);
  assert.match(modulesMd, /## user-flow.*exercise the observable flow/);
  assert.match(modulesMd, /Mandatory checks:.*e2e/);
  assert.match(modulesMd, /Acceptance tests:.*e2e/);
  assert.match(modulesMd, /Acceptance test touch:.*required/);
});

test("AGENTS.md always points to deliver; impact map adds stamp/task-start detail", () => {
  const withoutMap = renderAgentsMd(base);
  assert.match(withoutMap, /harness-kit deliver/);

  const withMap = renderAgentsMd({
    ...base,
    modules: [{ name: "api", role: "r", entry: ["src/a.ts"], owns: ["src/api/**"], checks: ["test"] }],
  });
  assert.match(withMap, /harness-kit deliver/);
  assert.match(withMap, /status=accepted/);
  assert.match(withMap, /task start/);
});
