import { chmodSync, existsSync } from "node:fs";
import { join } from "node:path";
import pkg from "../../package.json";
import {
  commitCodexLinkedInstall,
  isLinkedGitWorktree,
  prepareCodexLinkedInstall,
  type CodexLinkedInstallPlan,
  type CodexLinkedInstallTestHooks,
} from "../codex-linked-hooks";
import { gitRoot } from "../git";
import { inspectManagedFiles, writeManagedFiles, type ManagedFileInspection } from "../managed-files";
import { err, info, ok, warn } from "../util";

export type AgentTool = "claude" | "cursor" | "codex";
export const ALL_AGENTS: AgentTool[] = ["claude", "cursor", "codex"];

const SCRIPT_REL = ".agents/hooks/harness-agent-hook.sh";
const SCRIPT_MARK = "harness-kit-managed-hook (agent-lifecycle)";

function hookCommand(agent: AgentTool, event: "session-start" | "stop"): string {
  const run = `bash "$(git rev-parse --show-toplevel)/${SCRIPT_REL}" ${agent} ${event}`;
  const message = "harness-kit hook runner is missing or failed; run harness-kit run-checks and harness-kit verify manually";
  if (event === "stop") {
    const output =
      agent === "cursor"
        ? `{"followup_message":"${message}"}`
        : `{"decision":"block","reason":"${message}"}`;
    return `${run} || printf '%s\\n' '${output}'`;
  }
  return `${run} || { echo '${message}' >&2; exit 2; }`;
}

// This prefix is only a compatibility affordance for project-local development.
// Treat it as a path/command-word declaration, never as general shell syntax.
const SAFE_LOCAL_CLI_VALUE = String.raw`(?:"[-A-Za-z0-9_./:@%+,=]+"|'[-A-Za-z0-9_./:@%+,=]+'|[-A-Za-z0-9_./:@%+,=]+)`;
const LOCAL_CLI_OVERRIDE = new RegExp(
  String.raw`^(?:(?:env[ \t]+)?HARNESS_KIT_CMD=${SAFE_LOCAL_CLI_VALUE}[ \t]+)`,
);

/** Recognize only the command shape emitted by this installer. The optional
 * HARNESS_KIT_CMD assignment is a supported local-development override; the
 * runner invocation and client-specific failure fallback remain exact. */
export function isInstalledAgentHookCommand(
  command: string,
  agent: AgentTool,
  event: "session-start" | "stop",
): boolean {
  let candidate = command.trim();
  const override = candidate.match(LOCAL_CLI_OVERRIDE);
  if (override) candidate = candidate.slice(override[0].length).trim();
  return candidate === hookCommand(agent, event);
}

export function installedAgentHookRunnerScript(): string {
  return `#!/bin/sh
# ${SCRIPT_MARK}
# Generated by harness-kit install-hooks. Re-run install-hooks to update it.
AGENT="$1"
EVENT="$2"

block_infrastructure_failure() {
  message="harness-kit hook infrastructure failed; run harness-kit run-checks and harness-kit verify manually"
  if [ "$EVENT" = "stop" ]; then
    if [ "$AGENT" = "cursor" ]; then
      printf '{"followup_message":"%s"}\n' "$message"
    else
      printf '{"decision":"block","reason":"%s"}\n' "$message"
    fi
    exit 0
  fi
  echo "$message" >&2
  exit 2
}

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || block_infrastructure_failure
cd "$ROOT" || block_infrastructure_failure
[ -f .agents/manifest.yaml ] || block_infrastructure_failure

HK="\${HARNESS_KIT_CMD:-npx -y @erzhe/harness-kit@${pkg.version}}"
output=$($HK hook-event --repo "$ROOT" --agent "$AGENT" --event "$EVENT")
code=$?
[ "$code" -eq 0 ] || block_infrastructure_failure
[ -n "$output" ] && printf '%s\n' "$output"
exit 0
`;
}

function readJson(raw: string | null): Record<string, unknown> | null {
  if (raw == null) return {};
  try {
    const value = JSON.parse(raw);
    return value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : null;
  } catch {
    return null;
  }
}

function isManagedHook(hook: unknown, agent: "claude" | "codex", event: "session-start" | "stop"): boolean {
  return (hook as { type?: unknown })?.type === "command" &&
    typeof (hook as { command?: unknown })?.command === "string" &&
    isInstalledAgentHookCommand((hook as { command: string }).command, agent, event);
}

function withoutManagedGroupHooks(
  groups: unknown[],
  agent: "claude" | "codex",
  event: "session-start" | "stop",
): unknown[] {
  const result: unknown[] = [];
  for (const group of groups) {
    if (!group || typeof group !== "object" || Array.isArray(group)) {
      result.push(group);
      continue;
    }
    const hooks = (group as { hooks?: unknown }).hooks;
    if (!Array.isArray(hooks) || !hooks.some((hook) => isManagedHook(hook, agent, event))) {
      result.push(group);
      continue;
    }
    const remaining = hooks.filter((hook) => !isManagedHook(hook, agent, event));
    if (remaining.length) result.push({ ...(group as Record<string, unknown>), hooks: remaining });
  }
  return result;
}

function renderGroupStyle(current: string | null, rel: string, tool: "claude" | "codex"): string {
  const json = readJson(current);
  if (json == null) {
    throw new Error(`${tool}: ${rel} exists but is not valid JSON`);
  }
  if (json.hooks !== undefined && (!json.hooks || typeof json.hooks !== "object" || Array.isArray(json.hooks)))
    throw new Error(`${tool}: ${rel} hooks must be an object; refusing to replace an unknown existing shape`);
  const hooks = (json.hooks as Record<string, unknown> | undefined) ?? {};
  for (const [event, semanticEvent, command] of [
    ["SessionStart", "session-start", hookCommand(tool, "session-start")],
    ["Stop", "stop", hookCommand(tool, "stop")],
  ] as const) {
    if (hooks[event] !== undefined && !Array.isArray(hooks[event]))
      throw new Error(`${tool}: ${rel} hooks.${event} must be an array; refusing to replace an unknown existing shape`);
    const existing = Array.isArray(hooks[event]) ? (hooks[event] as unknown[]) : [];
    hooks[event] = [
      ...withoutManagedGroupHooks(existing, tool, semanticEvent),
      { hooks: [{ type: "command", command, timeout: 600 }] },
    ];
  }
  json.hooks = hooks;
  return JSON.stringify(json, null, 2) + "\n";
}

function cursorHasOurs(hook: unknown, event: "session-start" | "stop"): boolean {
  return typeof (hook as { command?: unknown })?.command === "string" &&
    isInstalledAgentHookCommand((hook as { command: string }).command, "cursor", event);
}

function renderCursor(current: string | null): string {
  const rel = ".cursor/hooks.json";
  const json = readJson(current);
  if (json == null) {
    throw new Error(`cursor: ${rel} exists but is not valid JSON`);
  }
  if (json.version == null) json.version = 1;
  if (json.hooks !== undefined && (!json.hooks || typeof json.hooks !== "object" || Array.isArray(json.hooks)))
    throw new Error(`cursor: ${rel} hooks must be an object; refusing to replace an unknown existing shape`);
  const hooks = (json.hooks as Record<string, unknown> | undefined) ?? {};
  if (hooks.sessionStart !== undefined && !Array.isArray(hooks.sessionStart))
    throw new Error(`cursor: ${rel} hooks.sessionStart must be an array; refusing to replace an unknown existing shape`);
  if (hooks.stop !== undefined && !Array.isArray(hooks.stop))
    throw new Error(`cursor: ${rel} hooks.stop must be an array; refusing to replace an unknown existing shape`);
  const sessionStart = Array.isArray(hooks.sessionStart) ? (hooks.sessionStart as unknown[]) : [];
  const stop = Array.isArray(hooks.stop) ? (hooks.stop as unknown[]) : [];
  hooks.sessionStart = [
    ...sessionStart.filter((hook) => !cursorHasOurs(hook, "session-start")),
    { command: hookCommand("cursor", "session-start"), timeout: 600 },
  ];
  hooks.stop = [
    ...stop.filter((hook) => !cursorHasOurs(hook, "stop")),
    { command: hookCommand("cursor", "stop"), timeout: 600, loop_limit: 8 },
  ];
  json.hooks = hooks;
  return JSON.stringify(json, null, 2) + "\n";
}

function renderCodexConfig(current: string | null): string {
  const raw = current ?? "";
  const lines = raw ? raw.replace(/\n$/, "").split("\n") : [];
  let featuresStart = -1;
  let featuresEnd = lines.length;
  for (let index = 0; index < lines.length; index++) {
    if (/^\s*\[features\]\s*(?:#.*)?$/.test(lines[index]!)) {
      featuresStart = index;
      continue;
    }
    if (featuresStart >= 0 && /^\s*\[.+\]\s*(?:#.*)?$/.test(lines[index]!)) {
      featuresEnd = index;
      break;
    }
  }

  if (featuresStart < 0) {
    if (lines.length && lines.at(-1) !== "") lines.push("");
    lines.push("[features]", "# harness-kit: required for project lifecycle hooks", "hooks = true");
  } else {
    const featureKeys: number[] = [];
    for (let index = featuresStart + 1; index < featuresEnd; index++) {
      if (/^\s*(?:hooks|codex_hooks)\s*=/.test(lines[index]!)) featureKeys.push(index);
    }
    if (featureKeys.length) {
      const first = featureKeys[0]!;
      const indent = lines[first]!.match(/^\s*/)?.[0] ?? "";
      lines[first] = `${indent}hooks = true`;
      for (const duplicate of featureKeys.slice(1).reverse()) lines.splice(duplicate, 1);
    } else {
      lines.splice(featuresStart + 1, 0, "# harness-kit: required for project lifecycle hooks", "hooks = true");
    }
  }
  return lines.join("\n") + "\n";
}

function currentByPath(inspections: readonly ManagedFileInspection[]): Map<string, string | null> {
  return new Map(inspections.map((inspection) => [inspection.relativePath, inspection.currentContent]));
}

function assertRenderedSourcesUnchanged(
  renderedFrom: readonly ManagedFileInspection[],
  transactionPreflight: readonly ManagedFileInspection[],
): void {
  const before = new Map(renderedFrom.map((inspection) => [inspection.relativePath, inspection]));
  if (before.size !== transactionPreflight.length)
    throw new Error("Agent hook target set changed after render");
  for (const current of transactionPreflight) {
    const previous = before.get(current.relativePath);
    if (
      !previous ||
      previous.absolutePath !== current.absolutePath ||
      previous.kind !== current.kind ||
      previous.currentContent !== current.currentContent ||
      previous.linkTarget !== current.linkTarget
    ) {
      throw new Error(`Agent hook source changed after render: ${current.relativePath}`);
    }
  }
}

function hookTargetPaths(agents: readonly AgentTool[]): string[] {
  const targets = [SCRIPT_REL];
  if (agents.includes("claude")) targets.push(".claude/settings.json");
  if (agents.includes("cursor")) targets.push(".cursor/hooks.json");
  if (agents.includes("codex")) targets.push(".codex/config.toml", ".codex/hooks.json");
  return targets;
}

function assertRunnerReplaceable(current: string | null, _force: boolean): void {
  if (current !== null && !current.includes(SCRIPT_MARK)) {
    throw new Error(`${SCRIPT_REL} exists and is not harness-kit-managed; --force never replaces foreign hooks`);
  }
}

export interface StopHookInstallTestHooks extends CodexLinkedInstallTestHooks {
  /** Deterministic seam for reproducing a concurrent edit after render. */
  beforeTransaction?: () => void;
}

export interface StopHookInstallOptions {
  force?: boolean;
  allowUserDispatcher?: boolean;
  testHooks?: StopHookInstallTestHooks;
}

export function installStopHooks(
  repo: string,
  agents: AgentTool[],
  opts: StopHookInstallOptions = {},
): number {
  const force = opts.force ?? false;
  const testHooks = opts.testHooks ?? {};
  if (!agents.length || agents.some((agent) => !ALL_AGENTS.includes(agent))) {
    err(`invalid --agents value; supported: ${ALL_AGENTS.join(",")}`);
    return 1;
  }
  try {
    repo = gitRoot(repo);
  } catch (error) {
    err(`agent hooks require a Git worktree: ${(error as Error).message}`);
    return 1;
  }
  if (!existsSync(join(repo, ".agents", "manifest.yaml"))) {
    err("agent hooks require .agents/manifest.yaml — onboard the repository first");
    return 1;
  }
  const linkedCodex = agents.includes("codex") && isLinkedGitWorktree(repo);
  if (linkedCodex && !opts.allowUserDispatcher) {
    err(
      "codex project hooks are ignored by current Codex CLI versions in linked worktrees; " +
        "no Agent hook files changed. Retry with `harness-kit install-hooks --repo . --stop --agents codex --allow-user-dispatcher`",
    );
    return 1;
  }
  let linkedPlan: CodexLinkedInstallPlan | null = null;
  if (linkedCodex) {
    try {
      linkedPlan = prepareCodexLinkedInstall(repo, installedAgentHookRunnerScript());
    } catch (error) {
      err(`codex linked-worktree dispatcher not installed: ${(error as Error).message} — no Agent hook files changed`);
      return 1;
    }
  }
  const rels = hookTargetPaths(agents);
  let inspections: ManagedFileInspection[];
  try {
    inspections = inspectManagedFiles(repo, rels.map((rel) => [rel, ""] as const));
  } catch (error) {
    err(`agent hooks not installed: ${(error as Error).message}`);
    return 1;
  }
  const current = currentByPath(inspections);
  const targets: Array<readonly [string, string]> = [];
  try {
    assertRunnerReplaceable(current.get(SCRIPT_REL) ?? null, force);
    targets.push([SCRIPT_REL, installedAgentHookRunnerScript()]);
    if (agents.includes("claude"))
      targets.push([".claude/settings.json", renderGroupStyle(current.get(".claude/settings.json") ?? null, ".claude/settings.json", "claude")]);
    if (agents.includes("cursor")) targets.push([".cursor/hooks.json", renderCursor(current.get(".cursor/hooks.json") ?? null)]);
    if (agents.includes("codex")) {
      targets.push([".codex/config.toml", renderCodexConfig(current.get(".codex/config.toml") ?? null)]);
      targets.push([".codex/hooks.json", renderGroupStyle(current.get(".codex/hooks.json") ?? null, ".codex/hooks.json", "codex")]);
    }
  } catch (error) {
    err((error as Error).message + " — no Agent hook files changed");
    return 1;
  }

  try {
    testHooks.beforeTransaction?.();
    writeManagedFiles(repo, targets, {
      authorize: (transactionPreflight) => assertRenderedSourcesUnchanged(inspections, transactionPreflight),
    });
    chmodSync(join(repo, SCRIPT_REL), 0o755);
  } catch (error) {
    err(`agent hooks not installed: ${(error as Error).message}`);
    return 1;
  }

  if (linkedPlan) {
    try {
      commitCodexLinkedInstall(linkedPlan, {
        beforeUserTransaction: testHooks.beforeUserTransaction,
        beforeRegistrationTransaction: testHooks.beforeRegistrationTransaction,
      });
    } catch (error) {
      err(
        `codex linked-worktree dispatcher not activated: ${(error as Error).message}; ` +
          "project files may be present but no worktree registration was trusted — rerun install-hooks",
      );
      return 1;
    }
  }

  ok(`${(current.get(SCRIPT_REL) ?? null) === null ? "installed" : "updated"} agent hook runner -> ${SCRIPT_REL}`);
  if (agents.includes("claude")) ok("claude: installed SessionStart + Stop hooks -> .claude/settings.json");
  if (agents.includes("cursor")) ok("cursor: installed sessionStart + stop hooks -> .cursor/hooks.json");
  if (agents.includes("codex")) {
    ok("codex: enabled project hooks -> .codex/config.toml");
    ok("codex: installed SessionStart + Stop hooks -> .codex/hooks.json");
    if (linkedPlan) {
      ok(`codex: installed linked-worktree dispatcher source -> ${join(linkedPlan.codexHome, "harness-kit", "codex-linked-dispatch-v1.cjs")}`);
      ok(`codex: registered this worktree -> ${join(linkedPlan.gitDir, "harness-kit", "codex-linked-dispatch-v1.json")}`);
    }
  }

  if (agents.includes("codex")) {
    warn(
      linkedPlan?.requiresRuntimeRefresh
        ? "codex: Orca mirrors this user Hook source into new terminals; start a fresh Orca Agent session, then review `/hooks` once"
        : linkedPlan
        ? "codex: run `/hooks` once to review and trust the Harness user dispatcher before it can run"
        : "codex: run `/hooks` to review and trust the new project hooks before they can run",
    );
  }
  info("\nSessionStart records the exact task base; every Stop reruns run-checks + verify.");
  info("After the first real agent session, run `harness-kit evidence`; no record means that client surface did not execute project hooks.");
  info(`Runner is pinned to @erzhe/harness-kit@${pkg.version}; override with HARNESS_KIT_CMD for local development.`);
  return 0;
}
