#!/bin/sh
# harness-kit-managed-hook (agent-lifecycle)
# Generated by harness-kit install-hooks. Re-run install-hooks to update it.
AGENT="$1"
EVENT="$2"

block_infrastructure_failure() {
  message="harness-kit hook infrastructure failed; run harness-kit run-checks and harness-kit verify manually"
  if [ "$EVENT" = "stop" ]; then
    if [ "$AGENT" = "cursor" ]; then
      printf '{"followup_message":"%s"}
' "$message"
    else
      printf '{"decision":"block","reason":"%s"}
' "$message"
    fi
    exit 0
  fi
  echo "$message" >&2
  exit 2
}

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || block_infrastructure_failure
cd "$ROOT" || block_infrastructure_failure
[ -f .agents/manifest.yaml ] || block_infrastructure_failure

if [ -n "${HARNESS_KIT_CMD:-}" ]; then
  output=$($HARNESS_KIT_CMD hook-event --repo "$ROOT" --agent "$AGENT" --event "$EVENT")
else
  # Resolve the pinned package outside the target repository. npm otherwise
  # mistakes a same-named source checkout for the requested published package.
  output=$(cd "${TMPDIR:-/tmp}" && npx -y @erzhe/harness-kit@0.4.1 hook-event --repo "$ROOT" --agent "$AGENT" --event "$EVENT")
fi
code=$?
[ "$code" -eq 0 ] || block_infrastructure_failure
[ -n "$output" ] && printf '%s
' "$output"
exit 0
